FROM python:3.9.2

WORKDIR /app

COPY settings.py /app/settings.py
COPY requirements/main_page_requirements.txt /app/requirements.txt
COPY actors_interface.py /app/actors_interface.py
COPY main_page_worker.py /app/main_page_worker.py

RUN pip install --upgrade pip
RUN python -m pip install --no-cache-dir -U 'dramatiq[rabbitmq, redis, watch]'==1.10.0
RUN python -m pip install --no-cache-dir -r requirements.txt

CMD ["python", "main_page_worker.py"]